openapi: 3.0.3
info:
  title: LMS HowTo API
  description: API documentation for LMS HowTo Video Service with AWS Cognito authentication.
  version: 1.0.0

servers:
  - url: https://33f0djvg5a.execute-api.ap-south-1.amazonaws.com/dev
    description: Production (AWS Lambda)
  - url: http://localhost:3000/local
    description: Local development

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    HowToVideo:
      type: object
      properties:
        title:
          type: string
          example: How to install LMS
        description:
          type: string
          example: Step-by-step installation guide
        video_url:
          type: string
          format: uri
        thumbnail_url:
          type: string
          format: uri
        provider:
          type: string
          example: s3
        duration_seconds:
          type: integer
          example: 180
        status:
          type: string
          enum: [draft, published]
        is_protected:
          type: boolean
        tags:
          type: array
          items:
            type: string
        metadata:
          type: object
        password:
          type: string

security:
  - bearerAuth: []

paths:
  /lms/createHowToVideos:
    post:
      summary: Create How-To Video
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HowToVideo"
      responses:
        '201':
          description: Video created
        '401':
          description: Unauthorized

  /lms/updateHowToVideo/{id}:
    put:
      summary: Update How-To Video
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Video ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                title: Updated title
                description: Updated description
                status: published
                is_protected: true
                password: plain-text-if-protected
                tags:
                  - updated
                  - tag
      responses:
        '200':
          description: Video updated
        '401':
          description: Unauthorized

  /lms/getHowToVideos:
    get:
      summary: Get How-To Videos
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: Page number
      responses:
        '200':
          description: List of videos
        '401':
          description: Unauthorized

  /lms/analytics:
    get:
      summary: Get Analytics
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Analytics data
        '401':
          description: Unauthorized

  /lms/login:
    post:
      summary: Login with Cognito
      description: Returns JWT tokens (ID token, access token, refresh token) for authentication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: ixltech
                password:
                  type: string
                  example: Admin234
      responses:
        '200':
          description: Login success
        '401':
          description: Invalid credentials